[package]
name = "shouty-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexopt = "0.3.0"

[[bin]]
name = "shouty"
test = false
bench = false
path = "src/main.rs"